name: Flutter Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.7'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: |
          flutter build apk --release

          APK_PATH=$(find . -type f -name "app-release.apk" -print -quit)

          if [ -z "$APK_PATH" ]; then
            echo "APK bulunamadÄ±."
            exit 1
          fi

          mkdir -p artifacts
          cp "$APK_PATH" test/app-release.apk

      - name: Upload APK
        uses: actions/upload-artifact@v5
        with:
          name: release-apk
          path: test/app-release.apk

